version: '2'
services:
  sonos_server:
    extends:
      file: docker/docker-compose.common.yml
      service: sonos_server
    network_mode: "host"
    volumes:
      - ./presets.json:/opt/app/presets.json
      - ./settings.json:/opt/app/settings.json

